/* Generated by tools/make-rail-icons.js. Edit that, not this. */
window.OrdisRailIcons = {
  "rivenRune": "<svg viewBox=\"0 0 24 24\" width=\"19\" height=\"19\" fill=\"none\" aria-hidden=\"true\" focusable=\"false\"><g stroke=\"currentColor\" stroke-width=\"2.1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 3.4 L20 19.6 L4 19.6 Z\"/><path d=\"M12 8.4 L16.4 17.4 L7.6 17.4\"/></g><circle cx=\"12\" cy=\"14.6\" r=\"1.5\" fill=\"currentColor\"/></svg>",
  "modCard": "<svg viewBox=\"0 0 24 24\" width=\"19\" height=\"19\" fill=\"none\" aria-hidden=\"true\" focusable=\"false\"><g stroke=\"currentColor\" stroke-width=\"2.3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5.4 4.6 H18.6 V15.9 L16.3 18.5 L14.7 17 L12.6 19.3 L10.5 17.5 L8.7 19.1 L5.4 16.2 Z\"/></g></svg>"
};
